FROM python:3.8.12-alpine

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk add --update --no-cache libxml2-dev libxslt-dev postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip
COPY ./lib_catalog/requirements.txt ./
RUN pip install -r requirements.txt

COPY ./lib_catalog ./
COPY ./lib_catalog/docker-entrypoint.sh .
ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]